# Generated by Django 2.1.2 on 2018-12-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CAN', 'Cancha'), ('PIS', 'Piscina'), ('CHU', 'Churrasquera'), ('GYM', 'Gym')], max_length=3)),
                ('nombre', models.CharField(max_length=30)),
                ('sector', models.CharField(max_length=30)),
                ('imagen', models.FileField(upload_to='area_comun')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('disp_desde', models.TimeField()),
                ('dip_hasta', models.TimeField()),
                ('tmp_maximo', models.TimeField()),
                ('estado', models.CharField(choices=[('H', 'Habilitado'), ('D', 'Deshabilitado'), ('M', 'Mantenimiento')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
