# Generated by Django 2.1.2 on 2018-12-07 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AreaComun', '0001_initial'),
        ('Propietario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('tmp_uso', models.TimeField()),
                ('id_area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AreaComun.AreaComun')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('area_social', models.ManyToManyField(related_name='detalle_reserva', through='Reserva.DetalleReserva', to='AreaComun.AreaComun')),
                ('id_propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Propietario.Propietario')),
            ],
        ),
        migrations.AddField(
            model_name='detallereserva',
            name='id_reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reserva.Reserva'),
        ),
    ]
